import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { Session } from '@supabase/supabase-js'
import { BarChart3, Boxes, BriefcaseBusiness, CarFront, CircleDollarSign, LogOut, Plus, ReceiptText, Users } from 'lucide-react'
import { supabase } from './lib/supabase'
import { money, summarize } from './lib/finance'

type Tab = 'dashboard' | 'revenues' | 'expenses' | 'employees' | 'services' | 'inventory' | 'access'
type Membership = { organization_id: string; role: 'owner'|'admin'|'operator'|'viewer'; display_name: string; organizations: { name: string; monthly_target: number } }
type Row = Record<string, unknown> & { id: string }
const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'America/Sao_Paulo' })
const month = () => today().slice(0, 7)
const labels: Record<Tab, string> = { dashboard: 'Visão geral', revenues: 'Receitas', expenses: 'Despesas', employees: 'Equipe', services: 'Serviços', inventory: 'Estoque', access: 'Acessos' }
const icons = { dashboard: BarChart3, revenues: CircleDollarSign, expenses: ReceiptText, employees: Users, services: CarFront, inventory: Boxes, access: BriefcaseBusiness }

function Auth() {
  const [signup, setSignup] = useState(false); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setMessage(''); const data = new FormData(event.currentTarget)
    const email = String(data.get('email')); const password = String(data.get('password'))
    const result = signup ? await supabase.auth.signUp({ email, password }) : await supabase.auth.signInWithPassword({ email, password })
    setMessage(result.error ? result.error.message : signup && !result.data.session ? 'Confira seu e-mail para confirmar o cadastro.' : '')
    setLoading(false)
  }
  return <main className="auth-shell"><section className="auth-brand"><div className="mark"><CarFront/></div><p>OPERAÇÃO • FINANÇAS • EQUIPE</p><h1>Seu lava-jato sob controle, em qualquer dispositivo.</h1><span>Dados centralizados, acesso por usuário, histórico financeiro preservado e segurança por empresa.</span></section><section className="auth-card"><h2>{signup ? 'Criar acesso' : 'Entrar no sistema'}</h2><p>{signup ? 'Use um e-mail válido e uma senha com pelo menos 8 caracteres.' : 'Acesse o ambiente seguro da sua empresa.'}</p><form onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="email" required /></label><label>Senha<input name="password" type="password" minLength={8} autoComplete={signup ? 'new-password' : 'current-password'} required /></label>{message && <div className="form-message">{message}</div>}<button disabled={loading}>{loading ? 'Aguarde…' : signup ? 'Criar conta' : 'Entrar'}</button></form><button className="link" onClick={() => { setSignup(!signup); setMessage('') }}>{signup ? 'Já tenho acesso' : 'Criar meu primeiro acesso'}</button></section></main>
}

function Onboarding({ displayName }: { displayName: string }) {
  const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const { error } = await supabase.rpc('bootstrap_organization', { p_name: String(data.get('organization')), p_display_name: String(data.get('name')) }); if (error) setError(error.message); else location.reload() }
  return <main className="center"><section className="auth-card"><div className="mark"><BriefcaseBusiness/></div><h2>Configurar sua empresa</h2><p>Você será o proprietário e poderá administrar os acessos.</p><form onSubmit={submit}><label>Nome da empresa<input name="organization" defaultValue="Lava Jato Expresso" required minLength={2}/></label><label>Seu nome<input name="name" defaultValue={displayName} required minLength={2}/></label>{error && <div className="form-message">{error}</div>}<button>Começar</button></form></section></main>
}

const fields = {
  employees: [['name','Nome','text'],['job_title','Cargo','text'],['salary','Salário','number'],['commission_percent','Comissão (%)','number'],['admission_date','Admissão','date']],
  services: [['name','Serviço','text'],['category','Categoria','text'],['price','Preço','number'],['duration_minutes','Duração (min)','number'],['operational_cost','Custo operacional','number'],['material_cost','Material','number']],
  inventory_items: [['name','Item','text'],['category','Categoria','text'],['quantity','Saldo inicial','number'],['unit','Unidade','text'],['unit_cost','Custo unitário','number'],['minimum_quantity','Estoque mínimo','number']],
  expenses: [['expense_date','Data','date'],['expense_type','Tipo (fixed/variable)','text'],['category','Categoria','text'],['description','Descrição','text'],['amount','Valor','number']],
} as const

function Crud({ table, organizationId, canWrite }: { table: keyof typeof fields; organizationId: string; canWrite: boolean }) {
  const qc = useQueryClient(); const [open,setOpen] = useState(false); const [error,setError] = useState('')
  const query = useQuery({ queryKey:[table,organizationId], queryFn: async () => { const { data,error }=await supabase.from(table).select('*').eq('organization_id',organizationId).order('created_at',{ascending:false}); if(error) throw error; return data as Row[] } })
  const save = useMutation({ mutationFn: async (payload: Record<string,unknown>) => { const { error }=await supabase.from(table).insert({ ...payload, organization_id:organizationId }); if(error) throw error }, onSuccess:()=>{qc.invalidateQueries({queryKey:[table,organizationId]});setOpen(false)}, onError:(e)=>setError(e.message) })
  async function archive(row: Row) { if(!confirm('Arquivar este registro? O histórico financeiro será preservado.')) return; const {error}=await supabase.from(table).update({active:false, ...(table==='employees'?{termination_date:today()}:{})}).eq('id',row.id); if(error) alert(error.message); else qc.invalidateQueries({queryKey:[table,organizationId]}) }
  async function voidExpense(row: Row) { if(!confirm('Estornar esta despesa? O registro permanecerá na auditoria.')) return; const {data:{user}}=await supabase.auth.getUser(); const {error}=await supabase.from('expenses').update({status:'void',voided_at:new Date().toISOString(),voided_by:user?.id}).eq('id',row.id); if(error) alert(error.message); else qc.invalidateQueries({queryKey:[table,organizationId]}) }
  async function moveInventory(row: Row) { const type=prompt('Digite entry para entrada ou exit para saída:','entry'); if(!type)return; const quantity=Number(prompt('Quantidade:','1')); if(!Number.isFinite(quantity)||quantity<=0){alert('Quantidade inválida.');return} const reason=prompt('Motivo da movimentação:','Ajuste operacional'); const {error}=await supabase.rpc('move_inventory',{p_item_id:row.id,p_type:type,p_quantity:quantity,p_reason:reason}); if(error)alert(error.message);else qc.invalidateQueries({queryKey:[table,organizationId]}) }
  function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const fd=new FormData(e.currentTarget); const payload:Object=Object.fromEntries(fields[table].map(([key,,type])=>[key,type==='number'?Number(fd.get(key)):fd.get(key)])); save.mutate(payload as Record<string,unknown>) }
  return <section><header className="page-title"><div><p>CADASTROS</p><h2>{table==='inventory_items'?'Estoque':table==='employees'?'Equipe':table==='services'?'Serviços':'Despesas'}</h2></div>{canWrite&&<button onClick={()=>setOpen(true)}><Plus size={18}/>Novo registro</button>}</header>{open&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><h3>Novo registro</h3><div className="form-grid">{fields[table].map(([key,label,type])=><label key={key}>{label}<input name={key} type={type} step={type==='number'?'0.01':undefined} defaultValue={type==='date'?today():undefined} required/></label>)}</div>{error&&<div className="form-message">{error}</div>}<footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button disabled={save.isPending}>Salvar</button></footer></form></div>}<DataState loading={query.isLoading} error={query.error?.message} empty={!query.data?.length}/>{query.data&&query.data.length>0&&<div className="table-wrap"><table><thead><tr>{fields[table].slice(0,5).map(([,label])=><th key={label}>{label}</th>)}<th>Status</th><th/></tr></thead><tbody>{query.data.map(row=><tr key={row.id} className={row.active===false||row.status==='void'?'muted':''}>{fields[table].slice(0,5).map(([key,,type])=><td key={key}>{type==='number'&&['salary','price','operational_cost','unit_cost','amount'].includes(key)?money(Number(row[key])):String(row[key]??'—')}</td>)}<td><span className="badge">{row.status==='void'?'Estornado':row.active===false?'Arquivado':'Ativo'}</span></td><td>{canWrite&&row.active!==false&&row.status!=='void'&&<>{table==='inventory_items'&&<button className="table-action" onClick={()=>moveInventory(row)}>Movimentar</button>}{table==='expenses'?<button className="table-action danger" onClick={()=>voidExpense(row)}>Estornar</button>:<button className="table-action" onClick={()=>archive(row)}>Arquivar</button>}</>}</td></tr>)}</tbody></table></div>}</section>
}

function Revenues({ organizationId, canWrite }:{organizationId:string;canWrite:boolean}) {
  const qc=useQueryClient(); const [open,setOpen]=useState(false); const [error,setError]=useState('')
  const query=useQuery({queryKey:['revenues',organizationId],queryFn:async()=>{const {data,error}=await supabase.from('revenues').select('*').eq('organization_id',organizationId).order('revenue_date',{ascending:false});if(error)throw error;return data as Row[]}})
  const refs=useQuery({queryKey:['revenue-refs',organizationId],queryFn:async()=>{const [s,e]=await Promise.all([supabase.from('services').select('*').eq('organization_id',organizationId).eq('active',true),supabase.from('employees').select('*').eq('organization_id',organizationId).eq('active',true)]);if(s.error)throw s.error;if(e.error)throw e.error;return{services:s.data as Row[],employees:e.data as Row[]}}})
  async function submit(ev:FormEvent<HTMLFormElement>){ev.preventDefault();const fd=new FormData(ev.currentTarget);const service=refs.data?.services.find(x=>x.id===fd.get('service_id'));const employee=refs.data?.employees.find(x=>x.id===fd.get('employee_id'));const payload={organization_id:organizationId,revenue_date:fd.get('revenue_date'),amount:Number(fd.get('amount')),payment_method:fd.get('payment_method'),customer_name_snapshot:fd.get('customer_name_snapshot'),service_id:service?.id??null,service_name_snapshot:service?.name??null,service_cost_snapshot:Number(service?.operational_cost??0)+Number(service?.material_cost??0),employee_id:employee?.id??null,employee_name_snapshot:employee?.name??null,commission_percent_snapshot:Number(employee?.commission_percent??0)};const{error}=await supabase.from('revenues').insert(payload);if(error)setError(error.message);else{setOpen(false);qc.invalidateQueries({queryKey:['revenues',organizationId]})}}
  async function voidRow(id:string){if(!confirm('Estornar esta receita? O registro ficará na auditoria.'))return;const {data:{user}}=await supabase.auth.getUser();const{error}=await supabase.from('revenues').update({status:'void',voided_at:new Date().toISOString(),voided_by:user?.id}).eq('id',id);if(error)alert(error.message);else qc.invalidateQueries({queryKey:['revenues',organizationId]})}
  return <section><header className="page-title"><div><p>FINANCEIRO</p><h2>Receitas</h2></div>{canWrite&&<button onClick={()=>setOpen(true)}><Plus size={18}/>Nova receita</button>}</header>{open&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><h3>Registrar atendimento</h3><div className="form-grid"><label>Data<input name="revenue_date" type="date" defaultValue={today()} required/></label><label>Cliente<input name="customer_name_snapshot" required/></label><label>Serviço<select name="service_id"><option value="">Sem vínculo</option>{refs.data?.services.map(x=><option key={x.id} value={x.id}>{String(x.name)}</option>)}</select></label><label>Funcionário<select name="employee_id"><option value="">Sem vínculo</option>{refs.data?.employees.map(x=><option key={x.id} value={x.id}>{String(x.name)}</option>)}</select></label><label>Valor<input name="amount" type="number" step="0.01" min="0.01" required/></label><label>Pagamento<select name="payment_method"><option>Pix</option><option>Dinheiro</option><option>Cartão</option></select></label></div>{error&&<div className="form-message">{error}</div>}<footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button>Salvar</button></footer></form></div>}<DataState loading={query.isLoading} error={query.error?.message} empty={!query.data?.length}/>{query.data&&query.data.length>0&&<div className="table-wrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Serviço</th><th>Funcionário</th><th>Pagamento</th><th>Valor</th><th>Status</th><th/></tr></thead><tbody>{query.data.map(r=><tr key={r.id} className={r.status==='void'?'muted':''}><td>{String(r.revenue_date)}</td><td>{String(r.customer_name_snapshot)}</td><td>{String(r.service_name_snapshot??'—')}</td><td>{String(r.employee_name_snapshot??'—')}</td><td>{String(r.payment_method)}</td><td>{money(Number(r.amount))}</td><td><span className="badge">{r.status==='void'?'Estornado':'Confirmado'}</span></td><td>{canWrite&&r.status==='posted'&&<button className="table-action danger" onClick={()=>voidRow(r.id)}>Estornar</button>}</td></tr>)}</tbody></table></div>}</section>
}

function Dashboard({organizationId,target}:{organizationId:string;target:number}){const revenue=useQuery({queryKey:['revenues',organizationId],queryFn:async()=>{const{data,error}=await supabase.from('revenues').select('amount,service_cost_snapshot,commission_percent_snapshot,status,revenue_date').eq('organization_id',organizationId);if(error)throw error;return data}});const expenses=useQuery({queryKey:['expenses',organizationId],queryFn:async()=>{const{data,error}=await supabase.from('expenses').select('amount,status,expense_date').eq('organization_id',organizationId);if(error)throw error;return data}});const stats=useMemo(()=>summarize(revenue.data??[],expenses.data??[],month()),[revenue.data,expenses.data]);const progress=target?Math.min(stats.gross/target*100,100):0;return <section><header className="page-title"><div><p>PAINEL EXECUTIVO</p><h2>Visão geral</h2></div><span className="period">Mês atual • {month()}</span></header><div className="kpis"><Kpi label="Receita" value={money(stats.gross)} tone="blue"/><Kpi label="Lucro líquido" value={money(stats.net)} tone={stats.net>=0?'green':'red'}/><Kpi label="Despesas + custos" value={money(stats.operatingExpenses+stats.directCosts)} tone="orange"/><Kpi label="Ticket médio" value={money(stats.ticket)} tone="violet"/></div><div className="dashboard-grid"><article className="panel"><p>META MENSAL</p><h3>{money(stats.gross)} <span>de {money(target)}</span></h3><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{progress.toFixed(1)}% alcançado</small></article><article className="panel"><p>RESULTADO OPERACIONAL</p><dl><div><dt>Atendimentos</dt><dd>{stats.count}</dd></div><div><dt>Custos diretos</dt><dd>{money(stats.directCosts)}</dd></div><div><dt>Despesas</dt><dd>{money(stats.operatingExpenses)}</dd></div></dl></article></div></section>}
function Access({organizationId,canManage}:{organizationId:string;canManage:boolean}){const qc=useQueryClient();const[open,setOpen]=useState(false);const[message,setMessage]=useState('');const query=useQuery({queryKey:['memberships',organizationId],queryFn:async()=>{const{data,error}=await supabase.from('memberships').select('*').eq('organization_id',organizationId).order('created_at');if(error)throw error;return data as Row[]}});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage('');const fd=new FormData(e.currentTarget);const{error}=await supabase.functions.invoke('invite-member',{body:{email:fd.get('email'),displayName:fd.get('displayName'),role:fd.get('role'),organizationId}});if(error)setMessage(error.message);else{setOpen(false);qc.invalidateQueries({queryKey:['memberships',organizationId]})}}return <section><header className="page-title"><div><p>SEGURANÇA</p><h2>Acessos</h2></div>{canManage&&<button onClick={()=>setOpen(true)}><Plus size={18}/>Convidar usuário</button>}</header>{open&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><h3>Convidar usuário</h3><div className="form-grid"><label>Nome<input name="displayName" required minLength={2}/></label><label>E-mail<input name="email" type="email" required/></label><label>Perfil<select name="role"><option value="operator">Operador</option><option value="viewer">Somente leitura</option><option value="admin">Administrador</option></select></label></div>{message&&<div className="form-message">{message}</div>}<footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button>Enviar convite</button></footer></form></div>}<DataState loading={query.isLoading} error={query.error?.message} empty={!query.data?.length}/>{query.data&&<div className="table-wrap"><table><thead><tr><th>Nome</th><th>Perfil</th><th>Status</th><th>Desde</th></tr></thead><tbody>{query.data.map(r=><tr key={String(r.user_id)}><td>{String(r.display_name)}</td><td>{String(r.role)}</td><td><span className="badge">{r.active?'Ativo':'Inativo'}</span></td><td>{String(r.created_at).slice(0,10)}</td></tr>)}</tbody></table></div>}</section>}
function Kpi({label,value,tone}:{label:string;value:string;tone:string}){return <article className={`kpi ${tone}`}><p>{label}</p><strong>{value}</strong></article>}
function DataState({loading,error,empty}:{loading:boolean;error?:string;empty:boolean}){if(loading)return <div className="state">Carregando dados…</div>;if(error)return <div className="state error">Não foi possível carregar: {error}</div>;if(empty)return <div className="state">Nenhum registro ainda.</div>;return null}

function Shell({session}:{session:Session}) { const [tab,setTab]=useState<Tab>('dashboard');const membership=useQuery({queryKey:['membership',session.user.id],queryFn:async()=>{const{data,error}=await supabase.from('memberships').select('organization_id, role, display_name, organizations(name, monthly_target)').eq('user_id',session.user.id).eq('active',true).maybeSingle();if(error)throw error;return data as unknown as Membership|null}});if(membership.isLoading)return <main className="center"><div className="loader"/></main>;if(!membership.data)return <Onboarding displayName={session.user.email?.split('@')[0]??'Proprietário'}/>;const m=membership.data;const canWrite=m.role!=='viewer';const canManage=['owner','admin'].includes(m.role);return <div className="app-shell"><aside><div className="logo"><div className="mark"><CarFront/></div><div><strong>Lava Jato</strong><span>EXPRESSO</span></div></div><nav>{(Object.keys(labels) as Tab[]).filter(key=>key!=='access'||canManage).map(key=>{const Icon=icons[key];return <button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={19}/>{labels[key]}</button>})}</nav><div className="profile"><span>{m.display_name.slice(0,2).toUpperCase()}</span><div><strong>{m.display_name}</strong><small>{m.role}</small></div><button title="Sair" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/></button></div></aside><main className="content"><div className="mobile-top"><strong>{m.organizations.name}</strong><select value={tab} onChange={e=>setTab(e.target.value as Tab)}>{Object.entries(labels).filter(([key])=>key!=='access'||canManage).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>{tab==='dashboard'&&<Dashboard organizationId={m.organization_id} target={Number(m.organizations.monthly_target)}/>} {tab==='revenues'&&<Revenues organizationId={m.organization_id} canWrite={canWrite}/>} {tab==='expenses'&&<Crud table="expenses" organizationId={m.organization_id} canWrite={canWrite}/>} {tab==='employees'&&<Crud table="employees" organizationId={m.organization_id} canWrite={canWrite}/>} {tab==='services'&&<Crud table="services" organizationId={m.organization_id} canWrite={canWrite}/>} {tab==='inventory'&&<Crud table="inventory_items" organizationId={m.organization_id} canWrite={canWrite}/>} {tab==='access'&&<Access organizationId={m.organization_id} canManage={canManage}/>}</main></div> }
export function App(){const[session,setSession]=useState<Session|null>(null);const[ready,setReady]=useState(false);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setReady(true)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);if(!ready)return <main className="center"><div className="loader"/></main>;return session?<Shell session={session}/>:<Auth/>}
